verify if have testing repository

diff --git a/usr/bin/calamares-biglinux b/usr/bin/calamares-biglinux
--- a/usr/bin/calamares-biglinux
+++ b/usr/bin/calamares-biglinux
@@ -19,43 +19,48 @@ if [ ! -f "/tmp/checksum_biglinux_ok.html" ]; then
     fi
 fi
 
-if [ "$(echo $(( $(date +%s) / 86400 )))" -gt "$(( $(cat /usr/share/bigbashview/bcc/apps/bigbashview-calamares/install_date) + 30 ))" ]; then
-    yad --image=emblem-warning --image-on-top --form --width=500 --height=100 --fixed \
-    --align=center \
-    --field=$"<b>Deseja prosseguir com a instalação dessa versão antiga assim mesmo?</b>
-    :LBL" \
-    --text $"O BigLinux é um sistema de atualizações semanais e esta versão foi lançada a mais de um mês.\nRecomendamos que faça o download de uma versão mais recente.
-    " \
-    --button=$" Continue":0 \
-    --button=$" Fechar":1 \
-    --center --on-top --borders=20 --title=$"Versão Desatualizada" \
-    --window-icon=emblem-warning
+#Testing Verify Start
+if [ "$(grep biglinux-testing /etc/pacman.conf)" != "" ]; then
 
-    
-    if [ "$?" = "1" ];then
-        exit 1
-    fi
-fi
+    if [ "$(echo $(( $(date +%s) / 86400 )))" -gt "$(( $(cat /usr/share/bigbashview/bcc/apps/bigbashview-calamares/install_date) + 30 ))" ]; then
+        yad --image=emblem-warning --image-on-top --form --width=500 --height=100 --fixed \
+        --align=center \
+        --field=$"<b>Deseja prosseguir com a instalação dessa versão antiga assim mesmo?</b>
+        :LBL" \
+        --text $"O BigLinux é um sistema de atualizações semanais e esta versão foi lançada a mais de um mês.\nRecomendamos que faça o download de uma versão mais recente.
+        " \
+        --button=$" Continue":0 \
+        --button=$" Fechar":1 \
+        --center --on-top --borders=20 --title=$"Versão Desatualizada" \
+        --window-icon=emblem-warning
 
-ruscherrelease=$(cat /etc/big-release | grep RELEASE | awk -F'=' '{print $2}')
-ruschertimestamp=$(cat /etc/big-release | grep TIMESTAMP | awk -F'=' '{print $2}')
-if [ "$(echo $ruscherrelease | wc -m)" -gt "11" ]; then
-    #if  [ "$(echo $(( $(date +%s) / 86400 )))" -gt "$(( $ruschertimestamp + 7 ))" ]; then
-        if [ -z "$(curl -s https://raw.githubusercontent.com/BigLinux-Package-Build/big-releases/main/testing | grep $ruscherrelease | grep -v "#")" ]; then
-            echo "ISO invalida"
-            yad --attach="$windowID" --image=emblem-warning --image-on-top --form --width=500 --height=100 --fixed \
-            --align=center \
-            --field=$"<b>Essa Versão de desenvolvimento está ultrapassada e não pode mais ser usada.</b>
-            :LBL" \
-            --button=$" OK":0 \
-            --center --on-top --borders=20 --title=$"Versão Desatualizada" \
-            --window-icon=emblem-warning
-            sudo pacman -R calamares-biglinux calamares --noconfirm
-            find $HOME -name calamares-biglinux.desktop -exec rm {} +
+        
+        if [ "$?" = "1" ];then
             exit 1
         fi
-    #fi
+    fi
+
+    ruscherrelease=$(cat /etc/big-release | grep RELEASE | awk -F'=' '{print $2}')
+    ruschertimestamp=$(cat /etc/big-release | grep TIMESTAMP | awk -F'=' '{print $2}')
+    if [ "$(echo $ruscherrelease | wc -m)" -gt "11" ]; then
+        #if  [ "$(echo $(( $(date +%s) / 86400 )))" -gt "$(( $ruschertimestamp + 7 ))" ]; then
+            if [ -z "$(curl -s https://raw.githubusercontent.com/BigLinux-Package-Build/big-releases/main/testing | grep $ruscherrelease | grep -v "#")" ]; then
+                echo "ISO invalida"
+                yad --attach="$windowID" --image=emblem-warning --image-on-top --form --width=500 --height=100 --fixed \
+                --align=center \
+                --field=$"<b>Essa Versão de desenvolvimento está ultrapassada e não pode mais ser usada.</b>
+                :LBL" \
+                --button=$" OK":0 \
+                --center --on-top --borders=20 --title=$"Versão Desatualizada" \
+                --window-icon=emblem-warning
+                sudo pacman -R calamares-biglinux calamares --noconfirm
+                find $HOME -name calamares-biglinux.desktop -exec rm {} +
+                exit 1
+            fi
+        #fi
+    fi
 fi
+#Testing Verify Stop
 
 # disable swap on disk
 for diskswap in $(blkid | grep 'TYPE="swap"' | grep -v zram | cut -f1 -d:)
@@ -330,28 +335,33 @@ if [ -e "/tmp/start_calamares" ]; then
     sudo QT_QUICK_BACKEND=software QSG_RENDER_LOOP=basic QT_XCB_GL_INTEGRATION=none /usr/bin/calamares-manjaro -d --platformtheme breeze
 fi
 
-ruscherrelease=$(cat /etc/big-release | grep RELEASE | awk -F'=' '{print $2}')
-if [ "$(echo $ruscherrelease | wc -m)" -gt "11" ]; then
-    #copiar log do calamares para home
-    cp /root/.cache/calamares/session.log /home/biglinux/calamares.log
-    chown biglinux:biglinux /home/biglinux/calamares.log
-    
-    send () {
-    sudo -u biglinux curl --upload-file "/home/biglinux/calamares.log" https://transfer.sh | tee "/home/biglinux/transfer.url"  | zenity --modal --progress --pulsate --no-cancel --auto-close --text $"Enviando, aguarde..."
-    sudo -u biglinux  brave-browser --new-window --no-sandbox $(cat "/home/biglinux/transfer.url")
-    } 
 
-    yad --buttons-layout=center \
-        --width=480 \
-        --button="Abrir":1 \
-        --button="Enviar para a nuvem":2 \
-        --button="Fechar":3 \
-        --title=$"calamares LOG" \
-        --text=$"\nDeseja visualizar ou enviar o arquivo de log da instalação para a nuvem?\ngerar um link para enviar no grupos de suporte.\n"
+#Testing Verify Start
+if [ "$(grep biglinux-testing /etc/pacman.conf)" != "" ]; then
 
-    case $? in
-        1) sudo -u biglinux kate /home/biglinux/calamares.log;;
-        2) send;;
-        3) echo "Fechando arquivo..." ;;
-    esac
+    ruscherrelease=$(cat /etc/big-release | grep RELEASE | awk -F'=' '{print $2}')
+    if [ "$(echo $ruscherrelease | wc -m)" -gt "11" ]; then
+        #copiar log do calamares para home
+        cp /root/.cache/calamares/session.log /home/biglinux/calamares.log
+        chown biglinux:biglinux /home/biglinux/calamares.log
+        
+        send () {
+        sudo -u biglinux curl --upload-file "/home/biglinux/calamares.log" https://transfer.sh | tee "/home/biglinux/transfer.url"  | zenity --modal --progress --pulsate --no-cancel --auto-close --text $"Enviando, aguarde..."
+        sudo -u biglinux  brave-browser --new-window --no-sandbox $(cat "/home/biglinux/transfer.url")
+        } 
+
+        yad --buttons-layout=center \
+            --width=480 \
+            --button="Abrir":1 \
+            --button="Enviar para a nuvem":2 \
+            --button="Fechar":3 \
+            --title=$"calamares LOG" \
+            --text=$"\nDeseja visualizar ou enviar o arquivo de log da instalação para a nuvem?\ngerar um link para enviar no grupos de suporte.\n"
+
+        case $? in
+            1) sudo -u biglinux kate /home/biglinux/calamares.log;;
+            2) send;;
+            3) echo "Fechando arquivo..." ;;
+        esac
+    fi
 fi
