clean files, change names, try fix open calamares, try fix open yad

diff --git a/usr/bin/calamares-biglinux b/usr/bin/calamares-biglinux
--- a/usr/bin/calamares-biglinux
+++ b/usr/bin/calamares-biglinux
@@ -409,37 +409,37 @@ QT_QUICK_BACKEND=software QMLSCENE_DEVICE=softwarecontext QTWEBENGINE_CHROMIUM_F
 if [ -e "/tmp/start_calamares" ]; then
     sudo cp -f /usr/share/biglinux/themes/biglinux/.config/kdeglobals /root/.config/kdeglobals
     sudo QT_QUICK_BACKEND=software QSG_RENDER_LOOP=basic QT_XCB_GL_INTEGRATION=none /usr/bin/calamares-manjaro -d
-fi
 
-#Calamares failed to install
-if [ "$(grep -w completion /root/.cache/calamares/session.log | grep -v bash-completion | rev | cut -d ":" -f1 | rev | sed 's/^[ \t]*//;s/[ \t]*$//')" != "succeeded" ];then
-# if [ "$(grep completion /root/.cache/calamares/session.log | rev | cut -d ":" -f1 | rev | sed 's/^ \+//')" = "failed" ];then
-    user=$(ls /home)
-    cp /root/.cache/calamares/session.log /home/$user/calamares.log
-    chown $user:$user /home/$user/calamares.log
-    
-    send () {
-    #sudo -u $user curl --upload-file "/home/$user/calamares.log" https://transfer.sh | tee "/home/$user/transfer.url"  | zenity --modal --progress --pulsate --no-cancel --auto-close --text $"Enviando, aguarde..."
-    sudo -u $user curl -data-binary -H "filename: /home/$user/calamares.log" https://filebin.net | tee "/home/$user/transfer.url"  | zenity --modal --progress --pulsate --no-cancel --auto-close --text $"Enviando, aguarde..."
-    
-    if [ -f /usr/bin/falkon ];then
-      sudo -u $user falkon https://filebin.net/$(cat "/home/$user/transfer.url" | grep '"id": "' | cut -f4 -d'"')
-    elif [ -f /usr/bin/brave ];then
-      sudo -u $user brave-browser --new-window --no-sandbox https://filebin.net/$(cat "/home/$user/transfer.url" | grep '"id": "' | cut -f4 -d'"')
-    fi
-    } 
+  #Calamares failed to install
+  if [ "$(grep -w completion /root/.cache/calamares/session.log | grep -v bash-completion | rev | cut -d ":" -f1 | rev | sed 's/^[ \t]*//;s/[ \t]*$//')" != "succeeded" ];then
+  # if [ "$(grep completion /root/.cache/calamares/session.log | rev | cut -d ":" -f1 | rev | sed 's/^ \+//')" = "failed" ];then
+      user=$(ls /home)
+      cp /root/.cache/calamares/session.log /home/$user/calamares.log
+      chown $user:$user /home/$user/calamares.log
+      
+      send () {
+      #sudo -u $user curl --upload-file "/home/$user/calamares.log" https://transfer.sh | tee "/home/$user/transfer.url"  | zenity --modal --progress --pulsate --no-cancel --auto-close --text $"Enviando, aguarde..."
+      sudo -u $user curl -data-binary -H "filename: /home/$user/calamares.log" https://filebin.net | tee "/home/$user/transfer.url"  | zenity --modal --progress --pulsate --no-cancel --auto-close --text $"Enviando, aguarde..."
+      
+      if [ -f /usr/bin/falkon ];then
+        sudo -u $user falkon https://filebin.net/$(cat "/home/$user/transfer.url" | grep '"id": "' | cut -f4 -d'"')
+      elif [ -f /usr/bin/brave ];then
+        sudo -u $user brave-browser --new-window --no-sandbox https://filebin.net/$(cat "/home/$user/transfer.url" | grep '"id": "' | cut -f4 -d'"')
+      fi
+      } 
 
-    yad --buttons-layout=center \
-        --width=480 \
-        --button=$"Abrir":1 \
-        --button=$"Enviar para a nuvem":2 \
-        --button=$"Fechar":3 \
-        --title=$"calamares LOG" \
-        --text=$"\nDeseja visualizar ou enviar o arquivo de log da instalação para a nuvem?\ngerar um link para enviar no grupos de suporte.\n"
+      yad --buttons-layout=center \
+          --width=480 \
+          --button=$"Abrir":1 \
+          --button=$"Enviar para a nuvem":2 \
+          --button=$"Fechar":3 \
+          --title=$"calamares LOG" \
+          --text=$"\nDeseja visualizar ou enviar o arquivo de log da instalação para a nuvem?\ngerar um link para enviar no grupos de suporte.\n"
 
-    case $? in
-        1) sudo -u $user kate /home/$user/calamares.log;;
-        2) send;;
-        3) echo "Fechando arquivo..." ;;
-    esac
+      case $? in
+          1) sudo -u $user kate /home/$user/calamares.log;;
+          2) send;;
+          3) echo "Fechando arquivo..." ;;
+      esac
+  fi
 fi
