teste de falha da instalação

diff --git a/usr/bin/calamares-biglinux b/usr/bin/calamares-biglinux
--- a/usr/bin/calamares-biglinux
+++ b/usr/bin/calamares-biglinux
@@ -335,33 +335,28 @@ if [ -e "/tmp/start_calamares" ]; then
     sudo QT_QUICK_BACKEND=software QSG_RENDER_LOOP=basic QT_XCB_GL_INTEGRATION=none /usr/bin/calamares-manjaro -d --platformtheme breeze
 fi
 
+#Calamares failed to install
+if [ "$(grep completion /root/.cache/calamares/session.log | rev | cut -d ":" -f1 | rev | sed 's/^ \+//')" = "failed" ];then
+    cp /root/.cache/calamares/session.log /home/biglinux/calamares.log
+    chown biglinux:biglinux /home/biglinux/calamares.log
+    
+    send () {
+    sudo -u biglinux curl --upload-file "/home/biglinux/calamares.log" https://transfer.sh | tee "/home/biglinux/transfer.url"  | zenity --modal --progress --pulsate --no-cancel --auto-close --text $"Enviando, aguarde..."
+    sudo -u biglinux  brave-browser --new-window --no-sandbox $(cat "/home/biglinux/transfer.url")
+    } 
 
-#Testing Verify Start
-if [ "$(grep biglinux-testing /etc/pacman.conf)" != "" ]; then
+    yad --buttons-layout=center \
+        --width=480 \
+        --button="Abrir":1 \
+        --button="Enviar para a nuvem":2 \
+        --button="Fechar":3 \
+        --title=$"calamares LOG" \
+        --text=$"\nDeseja visualizar ou enviar o arquivo de log da instalação para a nuvem?\ngerar um link para enviar no grupos de suporte.\n"
 
-    ruscherrelease=$(cat /etc/big-release | grep RELEASE | awk -F'=' '{print $2}')
-    if [ "$(echo $ruscherrelease | wc -m)" -gt "11" ]; then
-        #copiar log do calamares para home
-        cp /root/.cache/calamares/session.log /home/biglinux/calamares.log
-        chown biglinux:biglinux /home/biglinux/calamares.log
-        
-        send () {
-        sudo -u biglinux curl --upload-file "/home/biglinux/calamares.log" https://transfer.sh | tee "/home/biglinux/transfer.url"  | zenity --modal --progress --pulsate --no-cancel --auto-close --text $"Enviando, aguarde..."
-        sudo -u biglinux  brave-browser --new-window --no-sandbox $(cat "/home/biglinux/transfer.url")
-        } 
-
-        yad --buttons-layout=center \
-            --width=480 \
-            --button="Abrir":1 \
-            --button="Enviar para a nuvem":2 \
-            --button="Fechar":3 \
-            --title=$"calamares LOG" \
-            --text=$"\nDeseja visualizar ou enviar o arquivo de log da instalação para a nuvem?\ngerar um link para enviar no grupos de suporte.\n"
-
-        case $? in
-            1) sudo -u biglinux kate /home/biglinux/calamares.log;;
-            2) send;;
-            3) echo "Fechando arquivo..." ;;
-        esac
-    fi
+    case $? in
+        1) sudo -u biglinux kate /home/biglinux/calamares.log;;
+        2) send;;
+        3) echo "Fechando arquivo..." ;;
+    esac
+# elif [ "$(grep completion /root/.cache/calamares/session.log | rev | cut -d ":" -f1 | rev | sed 's/^ \+//')" = "succeeded" ];then
 fi
