added option to check if the default shell is bash or zsh, upon installation

diff --git a/usr/bin/calamares-biglinux b/usr/bin/calamares-biglinux
--- a/usr/bin/calamares-biglinux
+++ b/usr/bin/calamares-biglinux
@@ -46,12 +46,12 @@ fi
 ruscherrelease=$(cat /etc/big-release | grep RELEASE | awk -F'=' '{print $2}')
 ruschertimestamp=$(cat /etc/big-release | grep TIMESTAMP | awk -F'=' '{print $2}')
 
-# Default Shell in stable
-# userShell="/bin/bash"
-userShell="/bin/zsh"
-if [ -n "$(cat /etc/big-release | grep development)" ];then
-    # Default Shell in testing
-#     userShell="/bin/zsh"
+# Define the shells to be tested
+shells=("/bin/bash" "/bin/zsh")
+
+# Verifica se está em uma versão de desenvolvimento
+if [ -n "$(cat /etc/big-release | grep development)" ]; then
+    # Check the validity of the ISO
     if [ -z "$(curl -s https://raw.githubusercontent.com/BigLinux-Package-Build/big-releases/main/testing | grep $ruscherrelease | grep -v "#")" ]; then
         echo "ISO invalida"
         yad --attach="$windowID" --image=emblem-warning --image-on-top --form --width=500 --height=100 --fixed \
@@ -64,8 +64,43 @@ if [ -n "$(cat /etc/big-release | grep development)" ];then
         sudo pacman -R calamares-biglinux calamares --noconfirm
         find $HOME -name calamares-biglinux.desktop -exec rm {} +
         exit 1
+    else
+        # Try to use the defined shells
+        for shell in "${shells[@]}"; do
+            if [ -x "$shell" ]; then
+                userShell="$shell"
+                break
+            fi
+        done
+
+        # Check if a valid shell was found
+        if [ -z "$userShell" ]; then
+            echo "Nenhum shell válido encontrado."
+            exit 1
+        fi
     fi
 fi
+
+# # Default Shell in stable
+# # userShell="/bin/bash"
+# userShell="/bin/zsh"
+# if [ -n "$(cat /etc/big-release | grep development)" ];then
+#     # Default Shell in testing
+# #     userShell="/bin/zsh"
+#     if [ -z "$(curl -s https://raw.githubusercontent.com/BigLinux-Package-Build/big-releases/main/testing | grep $ruscherrelease | grep -v "#")" ]; then
+#         echo "ISO invalida"
+#         yad --attach="$windowID" --image=emblem-warning --image-on-top --form --width=500 --height=100 --fixed \
+#         --align=center \
+#         --field=$"<b>Essa Versão de desenvolvimento está ultrapassada e não pode mais ser usada.</b>
+#         :LBL" \
+#         --button=$" OK":0 \
+#         --center --on-top --borders=20 --title=$"Versão Desatualizada" \
+#         --window-icon=emblem-warning
+#         sudo pacman -R calamares-biglinux calamares --noconfirm
+#         find $HOME -name calamares-biglinux.desktop -exec rm {} +
+#         exit 1
+#     fi
+# fi
 
 # disable swap on disk
 for diskswap in $(blkid | grep 'TYPE="swap"' | grep -v zram | cut -f1 -d:)
