troca as verificações de internet e validade tudo para other_desktops

diff --git a/usr/bin/calamares-biglinux b/usr/bin/calamares-biglinux
--- a/usr/bin/calamares-biglinux
+++ b/usr/bin/calamares-biglinux
@@ -25,7 +25,7 @@ if [ ! -f "/tmp/checksum_biglinux_ok.html" ]; then
 fi
 
 #se a ISO foi gerada a mais de 30 dias emiter ALERTA
-if [ "$(echo $(( $(date +%s) / 86400 )))" -gt "$(( $(cat /usr/share/bigbashview/bcc/apps/bigbashview-calamares/install_date) + 30 ))" ]; then
+if [ "$(echo $(( $(date +%s) / 86400 )))" -gt "$(( $(cat /etc/big-release | grep UNIX_TIMESTAMP= | cut -d "=" -f2) + 30 ))" ]; then
     yad --image=emblem-warning --image-on-top --form --width=500 --height=100 --fixed \
     --align=center \
     --field=$"<b>Deseja prosseguir com a instalação dessa versão antiga assim mesmo?</b>
@@ -48,24 +48,22 @@ ruschertimestamp=$(cat /etc/big-release | grep TIMESTAMP | awk -F'=' '{print $2}
 
 # Default Shell in stable
 userShell="/bin/bash"
-if [ -n "$(cat /etc/big-release | grep development )" ];then
+if [ -n "$(cat /etc/big-release | grep development)" ];then
     # Default Shell in testing
     userShell="/bin/zsh"
-    #if  [ "$(echo $(( $(date +%s) / 86400 )))" -gt "$(( $ruschertimestamp + 7 ))" ]; then
-        if [ -z "$(curl -s https://raw.githubusercontent.com/BigLinux-Package-Build/big-releases/main/testing | grep $ruscherrelease | grep -v "#")" ]; then
-            echo "ISO invalida"
-            yad --attach="$windowID" --image=emblem-warning --image-on-top --form --width=500 --height=100 --fixed \
-            --align=center \
-            --field=$"<b>Essa Versão de desenvolvimento está ultrapassada e não pode mais ser usada.</b>
-            :LBL" \
-            --button=$" OK":0 \
-            --center --on-top --borders=20 --title=$"Versão Desatualizada" \
-            --window-icon=emblem-warning
-            sudo pacman -R calamares-biglinux calamares --noconfirm
-            find $HOME -name calamares-biglinux.desktop -exec rm {} +
-            exit 1
-        fi
-    #fi
+    if [ -z "$(curl -s https://raw.githubusercontent.com/BigLinux-Package-Build/big-releases/main/testing | grep $ruscherrelease | grep -v "#")" ]; then
+        echo "ISO invalida"
+        yad --attach="$windowID" --image=emblem-warning --image-on-top --form --width=500 --height=100 --fixed \
+        --align=center \
+        --field=$"<b>Essa Versão de desenvolvimento está ultrapassada e não pode mais ser usada.</b>
+        :LBL" \
+        --button=$" OK":0 \
+        --center --on-top --borders=20 --title=$"Versão Desatualizada" \
+        --window-icon=emblem-warning
+        sudo pacman -R calamares-biglinux calamares --noconfirm
+        find $HOME -name calamares-biglinux.desktop -exec rm {} +
+        exit 1
+    fi
 fi
 
 # disable swap on disk
